### ISSUE TITLE
Error message when ending combat

### ISSUE THREAD

**Issue by kaibis** [WBHarry/combat-hp-display#1]
![Screenshot 2022-05-03 122247](https://user-images.githubusercontent.com/104808690/166395986-9074a947-4a15-4e8d-bf1e-b21c3dfdb8a4.png)

I am receiving the following error message when I end combat.
After ending combat the health bars remain displayed.
This occurs to a mob (unmodified [5e] mob) and to PC tokens.

**Comment by WBHarry** [comment]
Version 1.0.1 was released with a fix to this issue. Thanks for finding it. 👍
