### ISSUE TITLE
[Feature] Different settings per token disposition

### ISSUE THREAD

**Issue by Doresain** [WBHarry/combat-hp-display#3]
Hey man, cool module, thank you!

It would be very cool if the out of combat display and combat display settings could be set differently for friendly/neutral/hostile tokens. I might want PC HP bars to pop open in combat (always for everyone) but leave the hostile HP bars obscured for players (always for owner).

**Comment by WBHarry** [comment]
Heya. Nice to see someone else likes the module :grin:
I just released version 1.0.3, introducing different handling for different token dispositions (friendly/neutral/hostile).

**Comment by Doresain** [comment]
You, sir, are awesome. Thanks again for the great work.
