### ISSUE TITLE
Settings not changing when saved

### ISSUE THREAD

**Issue by Doresain** [WBHarry/combat-hp-display#4]
Hey, so, after migrating from 1.02 to 1.03 settings changes wouldn't take. I did some poking around, and for some reason the old values weren't being overwritten on save - maybe something to do with the settings being instantiated as Numbers and being converted to Objects in 1.03?

In any case, once I manually set the settings to be objects everything worked fine and I could change them at will from the settings menu as intended.

If anyone else runs into this before it is fixed, just run these two commands in  the console and you'll be good to go:

game.settings.set('combat-hp-display','out-of-combat-display',{friendly: 10, neutral: 10, hostile: 10})
game.settings.set('combat-hp-display','combat-display',{friendly: 50, neutral: 50, hostile: 50})

**Comment by Doresain** [comment]
Yeah, confirmed this is a migration issue. 
1. Started a new server with 1.02 installed and the only mod activated.
2. Changed some settings.
3. Stopped the server and installed 1.03.
4. Tried to change settings - no dice, Stuck on the old value
5. Deleted server, started another fresh one.
6. Enabled 1.03 only, changed settings.
7. Worked like a charm.

So I suspect anyone migrating from 1.02 or earlier to 1.03 will have this problem.

**Comment by WBHarry** [comment]
I guess my migration script refused to take then!
I'll patch it into shape tomorrow :)

**Comment by WBHarry** [comment]
There we go. Seems I did a little quick change in the migration after I had already tested it, and that didn't pan out.
1.0.3.1 resolves the issue.
