### ISSUE TITLE
Feature request: Integration with Bar Brawl

### ISSUE THREAD

**Issue by roi007leaf** [WBHarry/combat-hp-display#5]
Feature request: Integration with Bar Brawl
as title says, bar brawl is more robust when it comes to bars, and i would love to only see them in combat and not outside combat, if you want i can send you how the bars object looks like

**Comment by WBHarry** [comment]
Heya. Bar Brawl does look interesting. Witty name since I immediately thought it had to do with..something else 😆 

I'll give it a look!

**Comment by roi007leaf** [comment]
@WBHarry Cool! let me know if you need any help because i already made some macros to change the visibility of the bars  for bar brawl and i'm also a developer :)

**Comment by WBHarry** [comment]
I just released version 1.1.0.0 (https://github.com/WBHarry/combat-hp-display/releases/tag/1.1.0.0), adding compatability with Bar Brawl.

I've finally had a bit of vacation, and got about to this. 🥳

**Comment by roi007leaf** [comment]
Cool, so how does it work now?
Out of the box supports bar brawl?
Best Regards,
Roi Horowitz

**Comment by WBHarry** [comment]
Yup. If Bar Brawl is activated in the world, then the module will handle things the 'Bar Brawl Way', otherwise it doesn't.
The module setting Display Bar Settings has the options available for 'Everyone' in the Bar Brawl system when using it, so it removes the 'When Controlled' options that are otherwise available. IE: 

- (Precombat Value - means that it won't change for combat at all)
- None
- Hover
- Always

**Comment by roi007leaf** [comment]
I think it's best to also add the option for the GM settings in bar brawl
(it's in the advanced bar settings) 😁

Best Regards,
Roi Horowitz

**Comment by WBHarry** [comment]
I'm not sure I agree. What is the usecase/situation you're thinking of where GMs and Players should see different things specifically in combat? 
The idea for the module is to show HP/Stamina/TempHP or whatever else is set up for tokens that enter combat. And I think if it's not desirable for players to see such things at all, then the Tokens in questions could just be set up as 'Always for Owner' or 'Owner Hover'.

**Comment by roi007leaf** [comment]
When using health estimate module combined, the players see the estimate
while I as GM see the bars

Best Regards,
Roi Horowitz

**Comment by roi007leaf** [comment]
Heres the situation.
My players are using the Health Estimate Module which tells them how injured the monster is without actually knowing the monster's hp status.
Me as a GM dont need those i only need the HP bars, BUT, i only need them in combat.
So Bar brawl has different settings for GM view, what i always do is set GM view to always and everyone else to NEVER.
and in the Health estimate module i set it up to only show up for players.
That way i have the bars and the players have the estimation without actually telling how much HP the monster has left (from looking at the bar they can tell)
So what i need from combat hp module to do is actually have an option to only show the hp bars in combat to the GM (or have another setting for the GM in the popup window)
That way i keep the immersion as a GM too :)
![image](https://user-images.githubusercontent.com/17231451/178131224-f9a9c94c-42c9-49af-9d5b-2beb14a2cc7a.png)
This is an image of the current behaviour (because of the health estimate module is on and also the bars)
And this is the GM view currently
![image](https://user-images.githubusercontent.com/17231451/178131241-fa7d1949-a45a-43ae-9680-ae7e27746cc0.png)

**Comment by roi007leaf** [comment]
So what you need to do is just add a checkbox or a toggle that says "GM only" 
and if it's true, set bar brawl values for the gmVisibility only
{
    "order": 0,
    "id": "bar1",
    "attribute": "attributes.hp",
    "max": null,
    "mincolor": "#FF0000",
    "maxcolor": "#80FF00",
    "position": "bottom-inner",
    "otherVisibility": 0, -> None for everyone
    "ownerVisibility": 0, -> None for owner
    "gmVisibility": 50, -> Always for GM
    "indentLeft": null,
    "indentRight": null,
    "shareHeight": false,
    "style": "user",
    "label": "",
    "invert": false,
    "subdivisions": null,
    "subdivisionsOwner": false,
    "fgImage": "",
    "bgImage": "",
    "opacity": null
}
Hit me up on Discord if you wanna talk about it :)
Roi007leaf#1015

**Comment by WBHarry** [comment]
I went ahead and released version 1.1.1.0 (https://github.com/WBHarry/combat-hp-display/releases/tag/1.1.1.0)
I included a GM Only toggle when using barbrawls. 📊

**Comment by roi007leaf** [comment]
Nice, thanks!

Best Regards,
Roi Horowitz
